### ISSUE TITLE
Use a stable compiler (tracking issue)

### ISSUE THREAD

**Issue by clbarnes** [pattonw/rust-pyn5#107]
Some nightly releases break due to some rust-numpy/pyo3 interaction ( https://github.com/rust-numpy/rust-numpy/issues/97#issuecomment-532877160 ).

Pyo3 currently requires a nightly compiler ( https://github.com/PyO3/pyo3/issues/5 ) due to the specialization feature ( https://github.com/rust-lang/rust/issues/31844 ).

**Comment by pattonw** [comment]
Looks like both pyo3 and pyo3-numpy are working on a stable branch now. I followed the changelogs and created a new branch `stable-build` which looks like it is almost working.
The blocker is now the `py.allow_threads` calls which panic with "\`std::cell::UnsafeCell<pyo3::ffi::PyObject>\` cannot be shared between threads safely".
Seems to be caused by the change in version 0.11 of numpy:
"To prevent undefined behavior, PyArray::as_slice and families are unsafe now. Please use the safe PyReadonlyArray::as_slice instead."
Looks like it needs to be updated in the n5 crate if we want to continue allowing threads

**Comment by pattonw** [comment]
Think its working now

**Comment by pattonw** [comment]
It is done. version 1.1.1 is on pypi, and built on stable rust
